### PR TITLE
EDS Fixes and Updated Doc - v2

### PR DESCRIPTION
**Pull request by whitead**
This PR fixes a bug for adaptive EDS, a bug that caused biases with coupling-constants of less than 1 to be significantly dampened and fixes some wording/examples in the documentation. It also links to a tutorial I've put together, [available here](http://thewhitelab.org/Blog/tutorial/2017/05/10/lammps-coordination-number-tutorial/), that gives a little more information on using EDS with coordination numbers.

Thanks!

@hockyg

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
Hi @whitead 

A couple of comments:
1. You are proposing to merge on master branch. EDS is available in v2.4 branch. If you want your changes to be available in the next release, you should rebase your request on v2.4. Otherwise it will go to v2.5 (end 2018).
2. I think you modified by mistake `src/multicolvar/CoordinationNumbers.cpp` . Could you rebase removing this (harmless) change?

Thanks!

**Comment by whitead** [comment]
Hi @GiovanniBussi, thanks for looking at this. I believe I've addressed 1 & 2.

**Comment by whitead** [comment]
@GiovanniBussi will these be merged to master or do I need to do another PR?

**Comment by GiovanniBussi** [comment]
@whitead sorry for the delay, v2.4 is regularly merged to master. This pull request has been merged already I think.

**Pull request merged**
