### PR TITLE
Cosinus switching function

### PR DESCRIPTION
**Pull request by king-michael**
##### Description

Implementation of a cosinus switching function as used by [Quigley2011 et al. J. Chem. Phys 2011, http://dx.doi.org/10.1063/1.3530288]

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by carlocamilloni** [comment]
Dear Michael could you also add a simple regtest, otherwise the feature is going to stay untested

**Comment by king-michael** [comment]
Can you give me a hint which regtests you are using for switchingfunctions?
Or at least in which subfolder i should place it?
Otherwise i will just create one in `basic` ?

**Comment by carlocamilloni** [comment]
You may extend regtest/basic/rt42 or add an rt42d/

**Comment by king-michael** [comment]
Travis seems to fail, but not because of changed files of this pull request:
* https://travis-ci.org/plumed/plumed2/jobs/435662219
```
The command "if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libfftw3-dev gsl-bin libgsl0-dev  libboost-serialization-dev ; fi" failed and exited with 100 during .
```
* https://travis-ci.org/plumed/plumed2/jobs/435662225
````
ERROR in test analysis/rt-wham/
```
The error:
```
/Users/travis/build/plumed/plumed2/regtest/analysis/rt-wham/tmp
../../scripts/run: line 129: 48748 Segmentation fault: 11  $mpi $valgrind $plumed driver $arg > out 2> err
FAILURE: exit code 139
mpirun(48748,0x700000081000) malloc: *** mach_vm_map(size=1125899906846720) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
[Traviss-Mac-1284:48748] *** Process received signal ***
[Traviss-Mac-1284:48748] Signal: Segmentation fault: 11 (11)
[Traviss-Mac-1284:48748] Signal code: Address not mapped (1)
[Traviss-Mac-1284:48748] Failing at address: 0x0
[Traviss-Mac-1284:48748] [ 0] 0   libsystem_platform.dylib            0x00007fff906c852a _sigtramp + 26
[Traviss-Mac-1284:48748] [ 1] 0   libsystem_platform.dylib            0x00007fff7c2974c0 _simple_asl_get_fd.pred + 0
[Traviss-Mac-1284:48748] [ 2] 0   mca_rml_oob.so                      0x000000010aff2daf orte_rml_oob_send_buffer_nb + 962
[Traviss-Mac-1284:48748] [ 3] 0   libopen-rte.40.dylib                0x000000010a857d47 pmix_server_log_fn + 434
[Traviss-Mac-1284:48748] [ 4] 0   mca_pmix_pmix2x.so                  0x000000010ae5aaeb server_log + 855
[Traviss-Mac-1284:48748] [ 5] 0   mca_pmix_pmix2x.so                  0x000000010ae8ef76 pmix_server_log + 1309
[Traviss-Mac-1284:48748] [ 6] 0   mca_pmix_pmix2x.so                  0x000000010ae7efae server_message_handler + 5187
[Traviss-Mac-1284:48748] [ 7] 0   mca_pmix_pmix2x.so                  0x000000010aeb6793 pmix_ptl_base_process_msg + 732
[Traviss-Mac-1284:48748] [ 8] 0   libevent-2.1.6.dylib                0x000000010a9910bb event_process_active_single_queue + 371
[Traviss-Mac-1284:48748] [ 9] 0   libevent-2.1.6.dylib                0x000000010a98e695 event_base_loop + 1170
[Traviss-Mac-1284:48748] [10] 0   mca_pmix_pmix2x.so                  0x000000010ae950d7 progress_engine + 26
[Traviss-Mac-1284:48748] [11] 0   libsystem_pthread.dylib             0x00007fff982a799d _pthread_body + 131
[Traviss-Mac-1284:48748] [12] 0   libsystem_pthread.dylib             0x00007fff982a791a _pthread_body + 0
[Traviss-Mac-1284:48748] [13] 0   libsystem_pthread.dylib             0x00007fff982a5351 thread_start + 13
[Traviss-Mac-1284:48748] *** End of error message ***
````

**Comment by carlocamilloni** [comment]
Thanks, I merged the code and we will investigate about the wham issue

Carlo

**Comment by GiovanniBussi** [comment]
@carlocamilloni in case you want this in v2.5, please also push the commit there (master and v2.5 are still identical).

**Comment by carlocamilloni** [comment]
Ok done

**Pull request merged**
