### PR TITLE
Added integration weights for Grid class 

### PR DESCRIPTION
**Pull request by valsson**
##### Description

Added a function to the Grid class to get the integration weights for the grids. For multi-dimensional integration, the weights are a product of one-dimensional weights. Currently only Trapezoidal weights are supported. 

This is function that I have been using for doing integrations in the VES code. I have changed all calls in the VES code to now call the function in the Grid class. 

I also added the integration weights to the calculations of the c(t) in MetaD.cpp (#401 by @invemichele). The results of the regtest (rt67) are the same since for periodic CVs all the weights are the same. 

##### Target release

I would like my code to appear in release v2.5

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers
- [x] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct.

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
@valsson @plumed/all this is (moderately) intrusive in the core. Should we merge it last minute to v2.5 or better merge to master?

**Comment by valsson** [comment]
After private communication with @invemichele I decided to revert the change to the calculation of c(t) in MetaD.cpp such that the weights are not used in the calculation of the integrals.

We agreed that this would be better since (adapted from @invemichele email):
1. If the weights are trapezoidal, they are different from 1 only on the boundary of the grid, and the integrand, exp(-beta*F), is generally always exponentially small there. (except for periodic CVs where all weights are the same due to how the grid for periodic CVs are constructed)
2. Higher order weights, such as simpson's are apparently not always better (see https://en.wikipedia.org/wiki/Trapezoidal_rule#Periodic_and_peak_functions )
3. It introduces an overhead, that might be small or not, depending on the dimension of the grid. you create a vector as big as the grid itself every time you update c(t).

Therefore, as this introduces overhead without much improvements, it is better just to sum over the grid without taking the weights into account. 

Unless you can see a situation where point 1 is not valid, i.e. exp(-beta*F) is not exponentially small at the boundary of the grid (for non-periodic CVs).

**Comment by GiovanniBussi** [comment]
@valsson does this mean that we should not merge this?

**Comment by valsson** [comment]
This is something that I use a lot in the VES code and after I reverted the changes to the MetaD.cpp, it only affects the VES code. In general, I think this could be useful for other things. I would like to have it internal in Grid, it would simplify some of my code. 

So, I would like it to be merged but then only to the master I would say.

**Comment by valsson** [comment]
I will close this pull request for now and look into it at a latter point.

**Pull request closed without merging**
