### PR TITLE
regtests

### PR DESCRIPTION
**Pull request by SilvioPipolo**
##### Description

fixed makefiles in piv regtests

##### Target release

I would like my code to appear in release __XXXXX__

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [X] new module contribution or edit of a module authored by you

##### Copyright

- [X] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [X] the module I added or modified contains a `COPYRIGHT` file with the correct license information. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct.

##### Tests

- [X] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by SilvioPipolo** [comment]
@GiovanniBussi sorry Giovanni, yes there was a problem with the Makefiles, now the regtests are run but I get an MPI strange error on some of them, but the colvar file produced is ok.

**Comment by GiovanniBussi** [comment]
@SilvioPipolo please check the [travis log](https://travis-ci.org/plumed/plumed2/jobs/428224438). It looks like:
- no regtest is run on piv (search for "/piv" string)
- there are a number of warnings about missing refs in the manual

Giovanni

**Comment by GiovanniBussi** [comment]
In addition, you apply astyle (see [here](https://travis-ci.org/plumed/plumed2/jobs/428224442))

**Comment by SilvioPipolo** [comment]
@GiovanniBussi Hello Giovanni, I think I fixed the regtest problem I had to force the commit of the Makefiles, but some conflicts appeared, I hope that's not my fault.

**Comment by GiovanniBussi** [comment]
@SilvioPipolo this pull request modifies all files, so there is something wrong.

Please reset it or restart from master branch from scratch in order to add your regtests. Thanks!

**Pull request closed without merging**
