### PR TITLE
restyling for the reweighting c(t) calculation

### PR DESCRIPTION
**Pull request by invemichele**
##### Description

Alternative implementation for the calculation of the reweighting constant _c(t)_. 
See #400 for details. 

##### Target release

I would like my code to appear in release v2.5

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct.

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on Travis-CI.

There are some small numerical differences in the multidimensional cases.

### CODE REVIEW

**Comment by gtribello** [comment]
Hello @invemichele 

If you want to get rid of the double grid that is fine.  You are probably right that it doesn't make much of a difference and you can just go over the grid.

On the frequency of update of the update of c(t), however, I wouldn't make the default on this 1 as my understanding is that the performance of the algorithm is crap if you update the estimate of c(t) every time you add a hill.  In fact this is what I did the first time I implemented the algorithm and Omar and I could never get this setting to give a sensible estimate of the FES.  I would thus have the input be that the user has to set REWEIGHTING_HILLS.

**Comment by valsson** [comment]
> I wouldn't make the default on this 1 as my understanding is that the performance of the 
> algorithm is crap if you update the estimate of c(t) every time you add a hill. In fact this is 
> what I did the first time I implemented the algorithm and Omar and I could never get this 
> setting to give a sensible estimate of the FES.

Regarding this, this was when using eq 14 in the JPCB 2015 paper, there the stride between updating c(t) matters as it is calculated as a finite difference. This is what we tried first where we saw this behavior. 

However, after consulting with Pratyush, we decided to use another more simpler equation to calculate c(t). This is equation 22 in the Ann. Rev. Phys. Chem 2016 paper and can be obtained by using equation 12 in equation 3 in the JPCB 2015 paper. There c(t) only depends on the current bias and is not calculated as a finite difference. Therefore, how often you update c(t) will not affect the results. It is only a question of overhead of how much the calculation costs. 

Omar

**Comment by invemichele** [comment]
I believe the error introduced with the single grid is very small, and furthermore is a systematic constant shift, so from a physical point of view should not affect the result of the reweighting.

From the performance side, I agree that there should be a keyword to change the stride of _c(t)_ update. I tried to show in #400 that even for a fast system (alanine in vacuum) with a big 300x300 grid there is very little overhead, so I think the default stride should be 1, but I don't mind also leaving it to 50, for sure is not going to be a problem.

From what I understand, the history of the _c(t)_ reweighting is a quite twisted one, and the old implementation is somehow a reflection of this. It would be nice to make it more straightforward for the future!
Regards,

Michele

**Comment by carlocamilloni** [comment]
I looked into the code and it is clear that the impact on performances is negligible, it is a few exp/log operations every time a Hill is added so unless this is done extremely frequently I don’t see any issue and also in that case one can still set the c(t) update to a higher period

**Comment by GiovanniBussi** [comment]
@carlocamilloni does this change syntax in an incompatible way? If so we should also annotate it in the changelog.

**Comment by carlocamilloni** [comment]
Yes the changelog must be updated

**Pull request merged**
