### PR TITLE
Small fix so that numerical forces in driver work with metadynamics

### PR DESCRIPTION
**Pull request by gtribello**
##### Description

I realized there was a bug in the routines that calculate the numerical forces that appears when you do metadynamics.  In essence as the sequence of plumed calls in driver is as follows:

prepareCalc
calc
<- store current value of bias ->
<- move atoms ->
prepareCalc
performCalcNoUpdate

you get a problem on a metadynamics update step as there is a huge difference in the value of the bias you get in the calc step and the prepareCalc step that happens after the atoms have been moved.  This difference is simply because there has been a call to update during the first call to calc as a Gaussian has been added to the metadynamics bias.

To be honest this is a pretty niche problem and I am not sure it needs fixing.  I have fixed it, however, by adding the following code after the call to calc in driver:

if(debugforces.length()>0) {
      virial.assign(9,real(0.0));
      forces.assign(3*natoms,real(0.0));
      p.cmd("prepareCalc");
      p.cmd("performCalcNoUpdate");
}

This ensures that the reference value of the bias that will be used when calculating the numerical derivatives is computed after the new Gaussian has been added.

##### Target release

It can probably be put in the latest release version.  I don't think it is that important though so we can just put it in master.

##### Type of contribution

- [x ] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct.

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by gtribello** [comment]
Incidentally @GiovanniBussi I am currently getting some errors on this branch with travis-ci which I don't understand.

**Comment by GiovanniBussi** [comment]
@gtribello it’s the problem related to #417. It’s fixed now (it doesn’t fail) thought there are parallelization problems (see Carlo’post).

I’ll chech this metad thing ASAP

**Comment by GiovanniBussi** [comment]
@gtribello should we merge this?

**Comment by gtribello** [comment]
@GiovanniBussi I think we might as well merge this.  So go ahead.

**Pull request merged**
