### PR TITLE
Atomic units

### PR DESCRIPTION
**Pull request by valsson**
##### Description

Add atomic units for energy (Hartree), length (Bohr), and time. Could be useful for ab initio MD codes. All numerical values based on CODATA 2014 (https://physics.nist.gov/cuu/Constants/).

##### Target release

I would like my code to appear in release v2.5

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
Thanks @valsson ! Would it be worth mentioning them in `src/setup/Units.cpp` as well so that they appear in the manual?

**Comment by valsson** [comment]
@GiovanniBussi, yes I agree. I will add a note to the manual. 

Looking at the code I was also thinking that the unit parsing could be improved. Like for example allowing both to use "A" and "Angstrom". Maybe also make the parsing case-insensitive. Also give a better error message if the unit string is written incorrectly (currently it gives an error "energy units should be positive". 

I could try to make some these improvement and commit to this pull request. What do you think?

**Comment by GiovanniBussi** [comment]
@valsson I am not sure allowing more choices is necessarily better.

In principle, now that constants are parsed using lepton, we could even redefine constants to have units in input values. E.g. `AT=3*nm_` where nm_ is set to 1 if units are nm, 10 if units are Angstroms etc. This is not possible yet since constants are global now, but once #250 will be closed it will be very easy (the set of constants will be contained in the PlumedMain object). Actually we never discussed about this, so maybe it is not even an interesting feature.

Anyway, if we increase the number of equivalent strings, allowing something like this would be a mess.

What do you think?

Of course this does not apply to your last suggestion (better error message), which I am sure would be absolutely an improvement.

**Comment by valsson** [comment]
Ok, I see you point, to have better choices it not necessarily better, especially if something like you suggest would be implemented. I like the idea to be able to have unit in the input values, that could be useful. 

To be consistent with the rest, I think there should be only one option for Hartree energies, do you think that "Ha" is ok or is that too ambiguous. 

I will then make some changes to the error message and push to the pull request.

**Comment by GiovanniBussi** [comment]
It looks like Ha is the [official abbreviation](https://en.wikipedia.org/wiki/Hartree) so I would use that (consistently with A/nm/etc).

Thanks a lot!

**Comment by valsson** [comment]
I pushed some changes to the pull request:
- Improved error handling for setting units in tools/units.cpp
- Updated manual for UNITS, possible choices for units are listed
- Improved output for UNITS such that numerical values are given in the log file

**Pull request merged**
