### PR TITLE
Proposal for mklib.sh modification

### PR DESCRIPTION
**Pull request by Iximiel**
##### Description

I'm changing the behaviour of mklib.sh in order to address the changes in #941, and make older codes compatible with the modifications in that PR. The script MUST be tested, and maybe reviewed, I'm still not quite convinced this is the best solution.

##### Target release

I would like my code to appear in the next release, it is related to some of the failing CI in the nest due to #941

##### Type of contribution

- [X] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules

##### Copyright

- [X] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
Can you check if the grep options you used are standard or if some new gnu version is needed?

In addition, you can add a regent. Look at the current regtest for the LOAD action, you can duplicate it or extend it

**Comment by Iximiel** [comment]
> Can you check if the grep options you used are standard or if some new gnu version is needed?
> 
> In addition, you can add a regent. Look at the current regtest for the LOAD action, you can duplicate it or extend it

Now I'm using grep without -P, and the grep commands are changed to address only the legacy includes (before any typo would be autocorrected with a simple, easy to ignore warning).

I redirected the echoes of the warning to the stderr, so they can be tested with err.reference

**Comment by Iximiel** [comment]
> I redirected the echoes of the warning to the stderr, so they can be tested with err.reference

Using the test features I injected a way to grep the warning line out of the stderr output

**Comment by GiovanniBussi** [comment]
@Iximiel there's still an error in the mac build, please check the log.

Don't worry about the failure in conda-linux, it's unrelated

**Pull request merged**
