### PR TITLE
Patch for quantum espresso 6.2

### PR DESCRIPTION
**Pull request by ralf-meyer**
##### Description

Adaptation of the quantum espresso 5.2.0 patch to the new file structure of quantum espresso 6.*

##### Target release

I would like my code to appear in release v2.4?

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. I also used the command `cd src && ./headers.sh mymodulename` in order to make sure the headers of the module are correct.

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
@ralf-meyer this is great, thanks a lot!

I would merge it as is. Could you please add just a sentence saying that you provided this patch in the `plumed_patch_info()` function in `patches/qespresso-6.2.config`? This would be useful in case someone wants to ask questions.

Also, in the way you opened it, the request will end up in master branch. If you want it to go to v2.4, I would recommend that you rebase it there. In case you are not able to do it yourself, just let me know and I will do it.

Finally, notice that there is a MacPorts package for quantum-espresso. After your patch has been merged, I will check if I can make a `quantum-espresso-plumed` subport. It should not be difficult, but I will be back if I have some problem with the patching procedure.

Thanks again!

Giovanni

**Comment by ralf-meyer** [comment]
First of all, thanks for the quick reply!

What exactly do you want the `plumed_patch_info()` to say? Just the name or do you need contact information (e.g. email-address)? 

To be honest: I am not sure were I want the commit to end up. I just wanted to make it available to others who encounter similar problems with newer versions of quantum-espresso, so I would leave that choice up to you.

Best regards,
Ralf

**Comment by GiovanniBussi** [comment]
OK I'll take care of that. Just give me (even with a private email) your email address. Thanks!

Giovanni

**Comment by GiovanniBussi** [comment]
Superseded by #312

**Pull request closed without merging**
