### PR TITLE
Ali esdw gyration

### PR DESCRIPTION
**Pull request by afarnudi**
##### Description

New implementation of Gyration radius using super duper maths

##### Target release

I would like this to be accepted in hack-the-tree and understand that this may never make to a release version

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct.

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by afarnudi** [comment]
Hi @gtribello.  This is Ali from the ESDW well actually it is you typing this message to yourself like some sort of lunatic.

**Comment by afarnudi** [comment]
Hi Gareth

I sent you an email just now. Don't know if your plane has landed yet.
I haven't done this before but I would guess that you will see the latest changes I have pushed to my branch and I don't need to do another 'pull request'.

Best,
Ali (ESDW)

**Comment by afarnudi** [comment]
Dear @gtribello 
Everything looks good except for the trace. I believe that the trace calculated using my code is correct or I am not aware of the output that the old code represents as the trace of the gyration tensor.

Next steps:
1- I will look for additional tests in the rt30 and rt36 folders that might help me find underlying bugs.
2- I will complete the documentation in the code.
3- I will get started on the e-cam readme file.

Please check if I have done everything that you have asked me so far.
Best,
Ali

**Comment by gtribello** [comment]
Hello @afarnudi 

I had a look at this stuff on the plane.  If you look at the definition of the trace in the old gyration code it is (a) not divided by the total weight and (b) the trace of the matrix is multiplied by two.  I checked on the plane and I see that if you compute the trace in this way you get numbers with your version that are consistent with the numbers that were output by the old code.

I don't know what the problem with the asphericity is but I found that I could reproduce the values the old code got if I did exactly what was done in the old code.

Separately there are some problems with the forces computed for all these things.  I am not sure what is wrong here.  I hope to perhaps take a look in the next few days though.

Gareth

**Comment by gtribello** [comment]
Hello @afarnudi

I worked out what was wrong with those forces.  In apply it needs to be:

ff[0] = 2*forcesToApply[0]*diff[0] + (forcesToApply[1]+forcesToApply[3])*diff[1] + (forcesToApply[2]+forcesToApply[6])*diff[2];
      ff[1] = (forcesToApply[1]+forcesToApply[3])*diff[0] + 2*forcesToApply[4]*diff[1] + (forcesToApply[5]+forcesToApply[7])*diff[2];
      ff[2] = (forcesToApply[2]+forcesToApply[6])*diff[0] + (forcesToApply[5]+forcesToApply[7])*diff[1] + 2*forcesToApply[8]*diff[2];

**Comment by afarnudi** [comment]
Hi @gtribello 
I am in Lyon. I have been fiddling around with the code since the morning. I can't get it to work because I don't understand what is happening in the background.

##The code I submitted:
rt30: checks out
rt36: Everything is consistent except for the trace. (it is smaller by a factor of 10)

##If I follow your instructions and:
1- trace -> 2xtrace, and
2-Do not divide the Gyration Tensor by the total mass,
rt36 test results:
trace values are consistent with the reference.
All other parameters are wrong :: I assume that I can fix this if I divide by the total mass upon calculation (like the old code) but these parts are written in the 'Parse' format (example: readInputLine( getShortcutLabel() + ": MATHEVAL ARG1=" + getShortcutLabel() + "_diag.vals-3 FUNC=sqrt(x) PERIODIC=NO");) and I need help understanding what is happening under the hood and what are my available variable calls.
 
rt30: Full of conflicts

#What I cannot get my head around:
The old code does not divide the Gyration Tensor by the total mass. But decides by the total mass at each stage of the calculation (mathematically makes sense). The code also calculates "factor"s for the derivatives. I cannot find where the derivatives are calculated in my code to implement the "factor"s if indeed they are the source of my problem.

**Comment by afarnudi** [comment]
By the way I implemented the force calculations you submitted

**Pull request closed without merging**
