### PR TITLE
Initial opes module

### PR DESCRIPTION
**Pull request by invemichele**
##### Description

New PLUMED module, that implements the OPES method, see https://pubs.acs.org/doi/10.1021/acs.jpclett.0c00497
For now only the well-tempered target is provided, but I plan to extend it for future PLUMED releases.

Documentation, regtests, headers and astyle should be fine.

I am providing two python scripts for post-processing in `src/opes/postprocessing`. They are useful but not essential, and I did not have time to implement them as a PLUMED command line tool. If you prefer, I can remove that folder and add instead an external link to them in the documentation.

##### Target release

I would like my code to appear in release 2.7

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [x] new module contribution or edit of a module authored by you

##### Copyright

- [ ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [x] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
@invemichele thanks! Related to this:
> I am providing two python scripts for post-processing in src/opes/postprocessing. They are useful but not essential, and I did not have time to implement them as a PLUMED command line tool. If you prefer, I can remove that folder and add instead an external link to them in the documentation.

I think it would be better to have them (a) somewhere else or (b) in a tutorial. If you put them in that directory nobody will find them. Ideally, they could be included as command like tool as you wrote.

**Comment by invemichele** [comment]
This time travis fails due to an `ERROR in test multicolvar/rt-waterbridge/`
In my module I only add a bias class, and do not touch the waterbridge multicolvar, so I have no idea why this happens...

**Comment by GiovanniBussi** [comment]
Should be fixed in c590bd3fb75b7eb3b3f92727bf5d5269f5d7a077 (just pushed)

> This time travis fails due to an `ERROR in test multicolvar/rt-waterbridge/`
> In my module I only add a bias class, and do not touch the waterbridge multicolvar, so I have no idea why this happens...

**Comment by invemichele** [comment]
This is the only error: `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`
Is there a way to rerun that build (beside pushing a new commit)?

**Comment by GiovanniBussi** [comment]
@invemichele to me it looks this can be merged. Do you confirm? Could you please add to [this file](https://github.com/plumed/plumed2/blob/master/CHANGES/v2.7.md) a notice about the addition of this new module? Thanks!

**Comment by invemichele** [comment]
I added the changelog, now it can be merged. thanks!

**Pull request merged**
