### PR TITLE
Add levenberg-marquadt to EDS, update defaults

### PR DESCRIPTION
**Pull request by hockyg**
##### Description

Update to EDS bias function with new features (Levenberg-Marquardt optimization) and defaults.

##### Target release

v2.5

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [x] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.
- [x] the module I added or modified contains a `COPYRIGHT` file with the correct license information. I also used the command `cd src && ./headers.sh mymodulename` in order to make sure the headers of the module are correct.

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
@hockyg can you fix the failure on travis? I've seen there is a line with a huge number. Perhaps you should use an exponential format (`%e` instead of `%f`)

**Comment by hockyg** [comment]
good point. I think it will have to be fixed precision, like %.8e. I'll try
that and make sure it doesn't break anything...

**Comment by GiovanniBussi** [comment]
@hockyg please apply `make astyle` again.

There is another failure on the pull request on travis, but that was small error on our side, just fixed 61c73b043760a18949c58fd130cdbf848923de73, so do not worry about that

**Comment by hockyg** [comment]
thanks!

**Pull request merged**
