### PR TITLE
Marco De La Pierre: added WALKERS_DIR option for WALKERS_MPI

### PR DESCRIPTION
**Pull request by marcodelapierre**
Make sure these boxes are checked before submitting your pull request:

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed succesfully on Travis.
- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers.

### CODE REVIEW

**Comment by marcodelapierre** [comment]
Hi guys, this is a small but useful mod in my opinion. 
I don't know anything about typical use of PLUMED with other MD codes, but in the case of LAMMPS we usually run replicas for MW-MetaD/PBMetaD in distinct folders.
Now, when WALKERS_MPI is used, all replicas need access to the HILLS files at restart time. Then it comes handy to be able to specify their path in the input file.
Marco

**Comment by GiovanniBussi** [comment]
Hi,

I have two comments:

- I am not sure this is needed. Can't you just use the following?

METAD FILE=/path/HILLS

- I think this is going to break cases where FILE is specified with full path.
   In other words, if you use

METAD FILE=/path/hillsfile

PLUMED will check for ./path/hillsfile which does not exist.
Notice that we have currently no way to regtest with absolute paths
since this would require the input file to be adjusted based on the
location of the regtest directory. That's why you don't see failures.

Users should change the input file to the following:

METAD FILE=hillsfile WALKERS_DIR=/path

This is counterintuitive since you should do it even when you don't
have multiple walkers.

Given these two points, I would prefer not to merge.

@marcodelapierre what do you think?

Giovanni

**Comment by marcodelapierre** [comment]
Hi @GiovanniBussi , thanks for the reply.

- The reason why we need to specify a path for WALKERS_MPI is that when using Parallel Bias MetaD there is a HILLS file per CV, and one can in principle use a relative large number of CVs, so that having to specify the path for each file name becomes annoying.
- On the other hand, I agree that when there is just one replica/one hills file one might want to specify the full path in the fill name. Also, we are fans of relative paths, but I have just realised that other users might be absolute path fans.

Therefore, I have updated the pull request with a new implementation for both MetaD and PBMetaD, where:
- when a single replica is adopted, the path is always absolute (as it was before);
- when multiple walkers are used, either disk or MPI, the default is absolute path, but using WALKERS_DIR permits to switch to relative paths.

Let me know whether this sounds more sensible (and useful) to you.

Marco

**Comment by marcodelapierre** [comment]
The 4 Mac builds on Travis are failing, but from the log file it looks like a machine issue, as the github server is not reachable.

**Comment by marcodelapierre** [comment]
Hi @GiovanniBussi ,
I had forgotten about the failed tests; they have now all passed.
Let me know if the branch is now good for merging, with the implementation modified according to your comments, as described above.
Marco

**Comment by GiovanniBussi** [comment]
@maxbonomi I wanted to merge this. I am ok with the changes to MetaD. Could you check if the changes in PBMetaD are also fine? Thanks! Giovanni

**Pull request merged**
