### PR TITLE
FIX - Changing the sign of the argument of the exponential in  LOWER_WALLS

### PR DESCRIPTION
**Pull request by Iximiel**
##### Description

This should solve #1091, see the issue for the problem

I want to benchmark the  (-x) version against the (abs(x)) version, but maybe that is a thing for another PR.

Shall we add a new test to check the sign in this and maybe other COLVARs?

##### Target release

I would like my code to appear in release __XXXXX__

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
I think the abs(x) vs -x has no impact on performance. I would use the most robust one.

Something that instead might be relevant (if you have many of these biases) is that they construct a lot of actions. @gtribello is it necessary? Are you aware that you can define intermediate values in lepton?

A test for it is [here](https://github.com/plumed/plumed2/blob/669793fc2818012bbd60c39882031e92ae5c5f4d/regtest/basic/rt-lepton/plumed.dat#L7) though it is not very instructive. But you can do something like:

```
FUNC=7*a^n;a=(x-x0);x0=3;n=2
```

The only counterintuitive thing is that values are parsed from right to left, so that you first use quantities then define them.

The example above should do `7*(x-3)^2`

The advantage is that:
- there is a single lepton call (performance gain should be measurable if you have many of these)
- lepton simplifies the expression (should be irrelevant in this case)

**Comment by carlocamilloni** [comment]
@Iximiel @GiovanniBussi @gtribello this needs to be retarget to 2.10, I would then merge it to fix the bug. The lepton change is about performances and can be done in a second moment

**Comment by carlocamilloni** [comment]
@Iximiel there are two lines added in multicolvardensity, why is that so?

**Comment by Iximiel** [comment]
> @Iximiel there are two lines added in multicolvardensity, why is that so?

I think that they are some things that comes from the various merges of master and v2.10
I am rebasing those changes away

**Pull request merged**
