### PR TITLE
Fix resolution function numerical issue

### PR DESCRIPTION
**Pull request by hmcezar**
##### Description

The way the resolution function was computed in the SAXS/SANS action could lead to some numerical issues due to computing the modified Bessel function with a large argument.
This could cause some `inf` and `NaN` depending on the sigmas and qs.

I have fixed this issue by implementing the [cephes](https://www.netlib.org/cephes/) function `i0e`, which computes `I_0(x) exp(-x)` and is less prone to overflow.

##### Target release

I would like my code to appear in release 2.9

##### Type of contribution

- [X] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [X] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [X] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by carlocamilloni** [comment]
@hmcezar sorry I merged and reverted it because you should target v2.9 if you want this to appear there

**Comment by hmcezar** [comment]
@carlocamilloni I think it was my mistake. The current 2.9 does not have the "old" implementation of the resolution function and your most recent fixes. I think it's better if it goes to `master` to be consistent with what we already have. Should I create another PR?

**Comment by carlocamilloni** [comment]
ok, I have reverted the revert, not the best but it is done

**Comment by hmcezar** [comment]
Thank you! And sorry for the mess. My bad.

**Pull request merged**
