### PR TITLE
Fix for updating of bias potential in VES_LINEAR_EXPANSION

### PR DESCRIPTION
**Pull request by valsson**
##### Description

This fixes an issue with updating of bias potential in VES_LINEAR_EXPANSION that is present for certain integrators that call the calculation of the bias multiple times and replica exchange. 

See discussion on PLUMED group: 
https://groups.google.com/d/msg/plumed-users/kPZu_tNZtgk/LrkS0EqrCQAJ

##### Target release

I would like my code to appear in release v2.5

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [x] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [x] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by valsson** [comment]
When testing these things I noticed that it possible to call update() multiple times within the same step which most likely  will lead to incorrect results. I don't think anyone would do something like that, but anyway I add a warning for this function.

**Comment by valsson** [comment]
@invemichele, you should look into this, briefly looking at your VesDeltaF it seems that it also suffers from the same issue that the averages needed for the gradient are accumulated in calculate(), and not update(). This will create problems with certain integrators (see [here](https://groups.google.com/d/msg/plumed-users/kPZu_tNZtgk/LrkS0EqrCQAJ)), like the one used in i-Pi, and replica exchange.

**Comment by invemichele** [comment]
Yes, my code has the same issue. I will fix it as you did, storing the values in a pointer and throwing a warning if update() is called before a new calculate().
thanks

**Comment by GiovanniBussi** [comment]
@valsson you would like to merge this to 2.5 as a bug fix, however the pull request points to master. Can you change it? Thanks!

**Comment by valsson** [comment]
Sorry about that, I have changed the PR to v2.5

**Pull request merged**
