### PR TITLE
Update to EnvironmentSimilarity

### PR DESCRIPTION
**Pull request by PabloPiaggi**
##### Description

Update the EnvironmentSimilarity multicolvar that is a part of the crystallization module. Changes:
- Allow the specification of chemical species in reference environments and in the simulation box through pdb files. This is useful to compare environments with more than one chemical species. As a result of this modification one can target complex crystal structures with any number of chemical species.
- A regtest for the new feature has been added
- Bug fix - The code now checks if environment pdb files exist before reading them. Thanks to @sigbjobo for mentioning that I should fix this.

This feature is **not** required for the upcoming Masterclass.

@gtribello do you have any suggestions regarding functionality or input syntax? Thank you.

##### Target release

I would like my code to appear in the master branch

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [x] changes to a module not authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by PabloPiaggi** [comment]
Before merging, I will try to fix the alert about the "missing return statement". I think it is harmless but I wil fix it nonetheless.

**Comment by PabloPiaggi** [comment]
> 

This is fixed now. Ready to merge from my side

**Comment by GiovanniBussi** [comment]
@gtribello any comment on this?

@PabloPiaggi you asked to merge on v2.8 but the PR is on master. Shall we backport this to v2.8 after merging?

I would suggest to do it only if this is a bug fix, and not if it includes new features.

Thanks!

**Comment by PabloPiaggi** [comment]
Thanks @GiovanniBussi !

**Pull request merged**
