### PR TITLE
Drop python 2

### PR DESCRIPTION
**Pull request by GiovanniBussi**
##### Description

This is an attempt to remove python 2 support (see #502).

I did not manage to install python 3 on travis on OSX install without MacPorts. The python stuff is still tested on Linux and on OSX with MacPorts, so it should not be a problem.

@dwhswenson could you please double check if the way I updated [setup.py](https://github.com/GiovanniBussi/plumed2/blob/drop-python-2/python/setup.py) is correct?

I also have a couple of questions about your hints.

**Pip**

Usually, upon release I upload the python package to PyPI (including cythonized cpp file).
At some point we will have simultaneous maintenance releases (2.5.x and 2.6.x).
If I upload both, do you think that `pip` will automatically pick the correct one
based on python version?

**Conda-forge**

For Conda-forge I guess I should modify [this file](https://github.com/conda-forge/py-plumed-feedstock/blob/master/recipe/meta.yaml).
Should I just add `skip: True # [py27]` to `build:` section?

Thanks!

Giovanni
 

##### Target release

I would like my code to appear in release __v2.6__

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
This pull request **fixes 1 alert** when merging bb7f4cd5f6f65c075ae7af627ca6d69ebe1e8081 into dcb5421869f85d46da3d58f83553ef8e929864d5 - [view on LGTM.com](https://lgtm.com/projects/g/plumed/plumed2/rev/pr-62520c45b9ef7a3dc970633c949ce3cf744d18ff)

**fixed alerts:**

* 1 for Accidental rethrow

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GiovanniBussi** [comment]
This pull request **fixes 1 alert** when merging 0f1ff232bc169e89e5757430feb4b91a00f2e241 into 9478ac0bc42c66edebb7ed5a24b5667a12d698f9 - [view on LGTM.com](https://lgtm.com/projects/g/plumed/plumed2/rev/pr-9be2a85d016b92be91b4873462c5c583f52c7752)

**fixed alerts:**

* 1 for Accidental rethrow

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by dwhswenson** [comment]
With the caveat that I haven't actually done any Py3-only releases (only been burned when others had problems with theirs), here are my thoughts:

#### `setup.py`

The `python_requires` looks good (although I don't know if you might have more strict requirements; e.g,. `>=3.3` -- most 2 and 3 compatible code took advantage of things added in 3.3 to enhance compatibility. Also, you might just want to say that you don't support anything older than 3.5 or 3.6. But none of that is likely to cause you problems; not much Python 3.2 out in the wild now.)

Rather than the `assert`, I'd recommend

```python
if sys.version_info < (3,):
    raise ImportError("your useful message here")
```

This is because a sufficiently foolish user could try to install with `python -O`, which disables `AssertionError`s. See also: https://python3statement.org/practicalities/, which includes an example of a useful message.

That link also discusses a few potential issues, mostly revolving around the idea that `pip` and `setuptools` have only supported this since 2016, so you may have problems from users who haven't updated their Python environments in the last 3 years.

#### `pip`

As I understand it, the `python_requires` is the main thing you need to get `pip`/PyPI to install correctly. So that should be fine.

One thing I just learned from the link above, though: it says that you *must* use `twine` to upload. (This is what I've always done for PyPI anyway.)

One thing you can do with PyPI is upload to [test.pypi.org](http://test.pypi.org), create a Python 2 environment, and try to pip-install from test.pypi. (If I recall, you need to create a separate account for test.pypi.) I run this sequence for releases of the code I have on PyPI (to ensure that everything needed for tests actually got into the package). From my `contact_map` package:

```
python setup.py sdist bdist_wheel
twine upload --repository-url https://test.pypi.org/legacy/ dist/*
```

```
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple contact_map
```
#### `conda`

My understanding is that there are two ways to disable Python 2 in conda. One is the `skip` directive, and the other is to use version constraints (i.e., `python >= 3` instead of just `python` in the `host` and `run` sections). I'm not sure which is preferred; I know that you need to use version constraints to qualify as a "noarch" package, but that won't matter for you (since PLUMED will certainly need to be compiled for each OS!)

I think you should be able to see which versions are being built from looking at the checks that are run in the PR in the feedstock, so that's the safety check.

**Comment by GiovanniBussi** [comment]
This pull request **fixes 1 alert** when merging d67a041974e09589058a02c900f2fe2092deeaaa into 3b19f16623c3f4d0e569fbc47c3b430df2874226 - [view on LGTM.com](https://lgtm.com/projects/g/plumed/plumed2/rev/pr-14e23752aa204e39f45a17697bed4770aca7247a)

**fixed alerts:**

* 1 for Accidental rethrow

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GiovanniBussi** [comment]
This pull request **fixes 1 alert** when merging cd9950f3dff545071f1db1eda0f48a56c077c9f0 into 099f97cf1e4216548178f541a1e51e741272e6a7 - [view on LGTM.com](https://lgtm.com/projects/g/plumed/plumed2/rev/pr-0aae19b096303e8416a3812bdfc0f42c0089d6d7)

**fixed alerts:**

* 1 for Accidental rethrow

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GiovanniBussi** [comment]
This pull request **fixes 1 alert** when merging 91ed00c8830fa880a152d4b741f35875929c74b7 into 40eff309153f9402059c0b65522dd4bd861bddc6 - [view on LGTM.com](https://lgtm.com/projects/g/plumed/plumed2/rev/pr-2367ad9af3082a7483d707197086a2f82f37ee21)

**fixed alerts:**

* 1 for Accidental rethrow

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GiovanniBussi** [comment]
This pull request **fixes 1 alert** when merging 51fe8eeabcb33eee8470ff577cee863d6216790b into 42f4b8b1c940ac07949e5932bfab0f3547031137 - [view on LGTM.com](https://lgtm.com/projects/g/plumed/plumed2/rev/pr-3c205c929a2009bf00ab517eb9a81e4e4e1c4fef)

**fixed alerts:**

* 1 for Accidental rethrow

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
