### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by tetsuyamorishita**
Changes in the LogMFD module

- TEMPPD keyword has been newly introduced, which allows for manually setting the temperature of the Boltzmann factor in the Jarzynski weight in LogPD.
- The output format has been modified to present the CV data in a more consistent way.
- The algorithm for evaluating the mean force at the initial MFD step has been modified to handle a continued MD trajectory that begins with non-zero timestep number.

##### Target release

I would like my code to appear in release v2.8.1 or later

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [X ] new module contribution or edit of a module authored by you

##### Copyright

- [ ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [X] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [X] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by tetsuyamorishita** [comment]
We have reopend the pull request on the master version following Giovanni's comments and it has successfully passed the test. We would appreciate it if you could merge this into 2.8.x or 2.9.
Many thanks!

**Comment by GiovanniBussi** [comment]
@tetsuyamorishita there is some problem with the regtest directory.

- You didn't add the relevant files (`Makefile`, possibly a plumed input), etc.
- You added `report.txt` files, that should not be there (they are an output)

What I recommend is that you separately clone again your proposed branch and make sure that:
- The tests are actually run
- When you run them, they do not modify any of the files tracked by git

Thanks!

**Comment by tetsuyamorishita** [comment]
We added the necessary files including Makefile and plumed.dat to tetsuyamorishita/plumed2 and we can indeed see there are these files on e.g. /regtest/logmfd/rt-logmfd-nve/.  You cannot see them? (Note that Makefile and plumed.dat are exatcly the same as the already stored ones, which may not be overwritten because of this?)

**Comment by GiovanniBussi** [comment]
OK I realized that the files I was asking for are already there.

Could you then just remove the `report.txt` files. Thanks!

**Comment by tetsuyamorishita** [comment]
Yes. We have deleted report.txt at regtest/logmfd/rt-logmfd-XXX/. Thank you.

**Pull request merged**
