### PR TITLE
added annfunc module

### PR DESCRIPTION
**Pull request by weiHelloWorld**
##### Description

Hi, this is related to a previous pull request: https://github.com/plumed/plumed2/pull/517.   We added an ANN (Artificial Neural Network) function for plumed **as a separate module**, which will be useful for constructing new collective variables and data analysis using a fully-connected feedforward neural network.  I have resolved the coding issues and added documentation, examples and regression tests for this module.  Let me know if there is any other things I would need to do.

##### Target release

I would like my code to appear in next release.

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [X] new module contribution or edit of a module authored by you

##### Copyright

- [ ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [X] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [X] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by carlocamilloni** [comment]
@weiHelloWorld thanks for the pull request. There are a couple of issues with cppcheck, see https://travis-ci.org/plumed/plumed2/jobs/578952556

check also in the user-doc folder for LOGMFDMOD.md, ISDB.md, VES.md to see how to add a module specific page in the documentation. The amount of documentation can be very minimal at the beginning but this is a good space to successively add specific tutorial etc.

**Comment by weiHelloWorld** [comment]
Hi @carlocamilloni Thanks for the suggestion!  I have updated the code and added the readme file accordingly.  But the code coverage checks seem to fail.  May I know what I should do for this?

Thanks!

**Comment by carlocamilloni** [comment]
Hi, about the coverage it looks like the test is not performed. Do you have a Makefile in regtest/annfunc? About the documentation please follow the example of plumed2/user-doc/LOGMFDMOD.md to add a basic documentation for your module

**Comment by carlocamilloni** [comment]
@weiHelloWorld thanks for your contribution! The module will be part of plumed 2.6, a beta version will be released shortly

**Comment by weiHelloWorld** [comment]
@carlocamilloni Sounds great!  Thank you so much for your help!

**Pull request merged**
