### PR TITLE
Various additions and changes in the VES module

### PR DESCRIPTION
**Pull request by valsson**
##### Description

Various additions and changes in the VES module. Almost all of the work was done by @bpampel. 

Including:  
  - New localized basis functions: Wavelets (BF_WAVELETS), Gaussians (BF_GAUSSIANS), and cubic splines (BF_CUBIC_B_SPLINES). 
  - New optimizer based on Adam (OPT_ADAM). 
  - New optimizer based on classical Robbins Monro stochastic gradient descent (OPT_ROBBINS_MONRO_SGD). 
  - Fixed a bug in VES_LINEAR_EXPANSION for multidimensional bias potential if one (or more) of the CVs is outside the range of the bias potential. 
  - Updated copyright header.
  - Other minor changes to fix compiler warnings. 

##### Target release

I would like my code to appear in release v2.8

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [x] new module contribution or edit of a module authored by you

##### Copyright

- [x] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.

Tests are currently running on GH Actions and with the latest changes, I expect them to pass. But I will make changes if needed. 
- [ ] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by valsson** [comment]
I have some issues with the numerics of the regtests for the wavelet generation. The derivate values seem to be sensitive to the compiler and lapack used. But I have fixed that by reducing the printout and making some other changes. However, now the failure is due to the fact that the fixzeros.sh script does not correctly handle values of the form `-0.00`. PR #761 should fix this and with that PR, this PR should pass the CI checks.

**Comment by valsson** [comment]
The LGTM errors ("Multiplication result may overflow 'int' before it is converted to 'size_type'.")
are related to things like this:
`std::vector<double> A(N*N)` 
where it complains that `N` is an `int`. This is the same error as in Matrix.h (line 271) and seems to be present elsewhere in the code. 
We could fix it by using `A( static_cast<size_t>(N) * static_cast<size_t>(N) )`. 
Should I do this?

**Comment by GiovanniBussi** [comment]
Don't worry about the lgtm warning. Let's see if the numerical issue is solved on GHA now (I guess you have the merge master in your branch and push again)

**Comment by valsson** [comment]
It passed on GH Action after the fixzeros.sh fix, but then I noticed in the coverage that the regtests were missing some parts of the code, so I added further tests. Once that has passed, this can be merged as I am concerned.

**Comment by GiovanniBussi** [comment]
Thanks!!

**Pull request merged**
