### PR TITLE
S2 contact model

### PR DESCRIPTION
**Pull request by valsson**
##### Description

NMR S2 contact model CV used in https://pubs.acs.org/doi/abs/10.1021/acs.jpclett.7b01770. 

I still need to add documentation, I will do that as soon as possible. But the code can be added now. 

##### Target release

I would like my code to appear in release v2.8

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [x] new module contribution or edit of a module authored by you

##### Copyright

- [ ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [x] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
Is there any reason for this to be added in colvar and not in a separate module?

**Comment by valsson** [comment]
Not really, it is just one file so I didn't think about putting it into a separate module. I could move it to the VES code module, though it is not related to that. Should I do that? If I do that, I would still have it appear under the CV in the manual.

**Comment by GiovanniBussi** [comment]
@valsson I would suggest to have a module with a single action, as we have several already.

**Comment by valsson** [comment]
I have moved the code to a separate module (s2cm)

**Comment by GiovanniBussi** [comment]
Thanks @valsson ! I am afraid you merged in some master-only change. Can you rebase this so that it is only based on v2.8 branch?

**Comment by valsson** [comment]
Ah, sorry, I have a mess of it. I am confused about what is the best way to do the rebase. How would you recommend to do it?

**Comment by valsson** [comment]
I have done it with cherry-picking, I will close this PR and open another one with the correct branch

**Comment by valsson** [comment]
Replaced by #768

**Pull request closed without merging**
