### PR TITLE
fixed VES examples in doc

### PR DESCRIPTION
**Pull request by invemichele**
##### Description

Fixing broken examples in VES module.
I started with my VES_DELTA_F, and then continued with the others... @valsson please have a look if the changes are fine for you.

I also noticed a small bug in how the doc is builded: when the LABEL keyword is removed, an empty line is left. 
See e.g. https://www.plumed.org/doc-master/user-doc/html/_m_a_x_e_n_t.html `LABEL=restraint` is removed and an empty line appears before the closing `...` . It should be deleted.

##### Target release

I would like my code to appear in release 2.6 and above

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers
- [x] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
I can merge this after @valsson approval.

Do you confirm that I will be able to then merge to v2.7 and v2.8? Or are there syntax changes or other conflicts? Thanks!

**Comment by invemichele** [comment]
Yes, I tested it on the master branch!

**Comment by valsson** [comment]
Looks fine to me, so this can be merged. Yes, I concur with @invemichele, you should be able to merge it to v2.7 and v2.8.

Thanks a lot @invemichele for taking care of this!

**Comment by GiovanniBussi** [comment]
Thanks!

Giovanni

**Pull request merged**
