### PR TITLE
Added benchmark command line tool

### PR DESCRIPTION
**Pull request by gtribello**
This tool runs plumed using a trajectory that is hard coded in the source code. It essentially works very much like driver, except the trajectory is fixed. You can use this to benchmark plumed calculations.  The advantage of having the separate code is the the profiles you get from this tool are not influenced by lots of I/O.

##### Description

Added tool for benchmarking plumed

##### Target release

I would like my code to appear in release v2.10

##### Type of contribution

- [ x] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [ x ] I added a new regtest or modified an existing regtest to validate my changes.
- [ x ] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by gtribello** [comment]
Hi @GiovanniBussi 

Here is a PR with the benchmark tool that I wrote for plumed.  Please feel free to modify it in whatever way you see fit.

**Comment by gtribello** [comment]
Hello @GiovanniBussi 

What is the status with this?  It looks like you did a lot of commits on this PR.  I think a lot of them are from a merge of master after you added the PyCV stuff? 

Do you want me to look at anything here?

**Comment by GiovanniBussi** [comment]
I am fixing a few stuff then I'll merge in master. I already merged master into this branch, and for some reasons, github doesn't understand that the only difference between this branch and master is the Benchmark.cpp file.

I added the possibility to load a previous version of the kernel, to do comparisons, and to run "forever" (until ctrl-C). I would like to also add the possibility to run with domain decomposition and MPI, because it's crucial for some other tests I am doing (see #1025)

I'll merge this in master today.

**Comment by gtribello** [comment]
OK that is great.  Thanks.

**Pull request merged**
