### PR TITLE
MAZE module for Plumed 2

### PR DESCRIPTION
**Pull request by jakryd**
##### Description

MAZE is a code that implements enhanced sampling methods for simulating ligand unbinding processes.

It is partly based on the following paper:

J. Rydzewski, and O. Valsson
*Finding Multiple Reaction Pathways of Ligand Unbinding*
Submitted (2018)
[arXiv](https://arxiv.org/abs/1808.08089)

A separate article describing the code will be published soon.

I tested the build (https://travis-ci.org/maze-code/plumed2-maze/builds/515118585), and it seems that jobs [#13.2](https://travis-ci.org/maze-code/plumed2-maze/jobs/515118587) and [#13.6](https://travis-ci.org/maze-code/plumed2-maze/jobs/515118591) failed, but not due to the maze module.

##### Target release

I would like my code to appear in release __v2.6__

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [X] new module contribution or edit of a module authored by you

##### Copyright

- [ ] I agree to transfer the copyright of the code I have written to the PLUMED
  developers or to the author of the code I am modifying.

- [X] the module I added or modified contains a `COPYRIGHT` file with the
  correct license information. I also used the command `cd src && ./header.sh
mymodulename` in order to make sure the headers of the module are correct.

##### Tests

- [X] I added a new regtest or modified an existing regtest to validate my
  changes.
- [ ] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
@jakryd could you fix the merge conflict?

I noticed that this commit also touches files out of the src/maze and regtests/maze paths. Please remove those changes. I would also suggest you to squash all your commits.

Thanks!

**Comment by jakryd** [comment]
@GiovanniBussi I fixed the merge conflict. I also tried to squash my commits but it fails.

**Comment by GiovanniBussi** [comment]
@jakryd You can try to:
- copy your code in a separate directory
- checkout master branch
- add your code in a single commit

**Comment by jakryd** [comment]
Thanks @GiovanniBussi. I caught up with all Plumed 2 changes and added my code in a single commit.

**Comment by GiovanniBussi** [comment]
@jakryd I think you still have all of your commits. What you should do is:

git checkout master
git reset --hard upstream/master # watch our this WILL REMOVE ALL YOUR CHANGES
... add your files  ...
git add *your files*
git commit

Giovanni

**Comment by jakryd** [comment]
@GiovanniBussi I needed to force-push the `maze-code:master` but it worked! Many thanks.

**Comment by GiovanniBussi** [comment]
@jakryd I noticed you used a GPL license rather than L-GPL. Is this intended?

I think that's fine, but notice that so far all other modules are either L-GPL or less restrictive (BSD-like or LAPACK/BLAS-like).

I would prefer if you also adopt a less restrictive license, otherwise we would technically have to enforce that no-one distributes binaries including the maze module linked with non-GPL programs.

**Comment by GiovanniBussi** [comment]
@jakryd I checked your code in more detail. It looks like you are registering the following keywords:

````
LOSS
MEMETIC_SAMPLING
OPTIMIZER_BIAS
RANDOM_ACCELERATION_MD
RANDOM_WALK
SIMULATED_ANNEALING
STEERED_MD
````

Some names look very general. Could you prepend them with a `MAZE_` prefix?

Thanks!

**Comment by GiovanniBussi** [comment]
Also please double check the cppcheck job that fails [on travis-ci](https://travis-ci.org/plumed/plumed2/jobs/516527745). The log is very long (I need to force some ASMJIT macros to make it shorter, sorry for that) but if you download the raw log you can open it with an editor and check at the end the reported error. Thanks!

**Comment by GiovanniBussi** [comment]
Yet another comment: please go to `src/` and type `./header.sh maze` to fix your headers. This script automatically takes care of copyright header and of cpp guards, so the guards might end up duplicated wrt those you already added (you should fix them or I guess the code will not compile).

**Comment by jakryd** [comment]
@GiovanniBussi thanks again for helping me. I've corrected all the issues you noticed.

**Pull request merged**
