### PR TITLE
Let GROMACS runtime logs show PLUMED patch active

### LINKED ISSUE #737: allow GROMACS log files to report that the code is patched by PLUMED
In GROMACS, we have for a few years enabled users to do `cmake -DGMX_VERSION_STRING_OF_FORK=PLUMED` and that will show up in the GROMACS version string e.g. in log files. This is useful for users running their own forks making sense of their log files later on, as well as for developers reading forum posts or bug reports knowing what versions were used. Troubleshooting GROMACS users' performance questions can go much better if the co-existence of PLUMED is known.

In PLUMED's approach, it seems straightforward to patch the relevant cmake file in GROMACS that declares that variable so that its default value is `PLUMED` and the GROMACS mechanism will work the same way. Is such a patch to PLUMED welcome? If so, I will prepare it.

Would the PLUMED developers prefer also that the PLUMED version appear there? If so, is there a mechanism for that to be updated each time the PLUMED version is updated?

### PR DESCRIPTION
**Pull request by mabraham**
##### Description

Knowing which PLUMED version has patched GROMACS is potentially valuable information for GROMACS and PLUMED users and developers troubleshooting their runs.

Closes #737

##### Target release

I would like my code to appear in release 2.7 and master

##### Type of contribution

- [X] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [X] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by mabraham** [comment]
@GiovanniBussi Here's my attempt at patching the latest GROMACS config. Ideally we'd put a pair of "" around the version, but I couldn't work out how to do that with awk. So long as the PLUMED_VERSION doesn't contain spaces then the current code is OK. Once we're happy with this, then porting to the other configs and perhaps back to the 2.7 branch would be desirable.

Only recent GROMACS versions have this GMX_VERSION_STRING_OF_FORK variable, but if it's not found then the awk operation is a no-op, so we don't need extra complexity to handle that.

**Comment by GiovanniBussi** [comment]
Thanks @mabraham !

I'll merge and backport to v2.7 and to gmx 2020 patch (the modified file seems already present [there](https://github.com/gromacs/gromacs/blob/release-2020/cmake/gmxVersionInfo.cmake)).

**Comment by mabraham** [comment]
> @mabraham I added a "plumed-" prefix to the string, does it make sense?
> 
> See [9b50841](https://github.com/plumed/plumed2/commit/9b50841c8d8cc0801740a104d1502a1db3561363)

Sure, that's good!

**Comment by mabraham** [comment]
> Thanks @mabraham !
> 
> I'll merge and backport to v2.7 and to gmx 2020 patch (the modified file seems already present [there](https://github.com/gromacs/gromacs/blob/release-2020/cmake/gmxVersionInfo.cmake)).

Yes, present since 2020

**Comment by GiovanniBussi** [comment]
@mabraham is it possible that GROMACS uses the modified version to download the set of regression tests? I am asking because a user reported [this](https://groups.google.com/d/msgid/plumed-users/a9a3b8b8-b8c4-4fd2-91df-02313f32ffbbn%40googlegroups.com?utm_medium=email&utm_source=footer) on our mailing list. Thanks!

**Comment by mabraham** [comment]
Thanks for the question. Yes, that is what is happening. Fix proposed for
2022.1 at https://gitlab.com/gromacs/gromacs/-/merge_requests/2587.

Unfortunately the issue won't be fixed in 2020 or 2021 branches (out of
support and not serious enough, respectively), so I suggest you suggest
users do a similar fix themselves, or put such a fix into the PLUMED patch,
or set a correct REGRESSIONTEST_VERSION value in the cache (which will not
be overridden by the current buggy logic).

Mark

**Comment by mabraham** [comment]
That fix is now incorporated in the branch from which 2022.1 will be made, in due course, so the fix is expected to appear there.

**Pull request merged**
