### PR TITLE
Some fixes to VES optimizer file output

### PR DESCRIPTION
**Pull request by valsson**
##### Description

This PR fixes two issues with file output in the VES optimizer: 

- Made sure that all relevant output files are written out at the final step when shutting down the simulation. This solves issues reported by @PabloPiaggi with restarting when there is a mismatch been the output of files and the number of MD steps.

- Fixed an off-by-one bug in the output of target distribution averages. The bug only affects the output and does not affect results. The bug also affected the output of coefficients when using a bias cutoff. This is a minor issue that should not affect users. 

I have done the changes to v2.4 as discussed with @GiovanniBussi, but they should be merged to v2.5, v2.6, and the master

##### Target release

I would like my code to appear in release v2.4, v2.5, v2.6, master

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [x] new module contribution or edit of a module authored by you

##### Copyright

- [ ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [x] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
@valsson you opened by mistake a pull request to master branch.

I'll take care of it. I am running right now tests for your branch separately [here](https://travis-ci.org/plumed/plumed2/builds/640998562). I'll be back if I see failures or conflicts in merging

Thanks!

**Comment by GiovanniBussi** [comment]
@valsson it looks like there are failures on travis ci. Can you double check? [this is the relevant build](https://travis-ci.org/plumed/plumed2/builds/640998562)

**Comment by valsson** [comment]
@GiovanniBussi sorry for mistake in doing PR to the master instead of v2.4, I didn't pay enough attention. Thanks for taking care of it! 

I looked at the failing regtest, it is numerics issue with one of the grid files, the last digit in one line is -1. In principle, I should have a format option for these files to avoid these kind of issues, but it is not implemented at the moment (I might do it on the master soon), and I haven't observed before that I was getting different results on my Mac and on travis. To fix it, I just changed the reference file by hand. I will take a look at the build later to see if that fixes it.

**Comment by valsson** [comment]
Okay, then the issue is that it fails for the MacOS test. I have just removed the reference file for the failing file, so the failure is avoided. Anyway, this particular file is not an important part of this regtest, so it should not matter if it is not checked.

**Pull request merged**
