### PR TITLE
opes: fix for too small initial sigma estimates

### PR DESCRIPTION
**Pull request by carlocamilloni**
@invemichele

### CODE REVIEW

**Comment by carlocamilloni** [comment]
We got a case were the CV was almost always 0 in the initial stage and the code segfaulted

**Comment by invemichele** [comment]
Thanks!
Do you think this is a problem that can arise only with the initial estimate or could happen also in the middle of the simulation?

In the first case I would put an error, so the user knows there is something wrong with the adaptive sigma. But if it can happen in the middle of a simulation it is probably better not to kill it, but just send a warning.

In both cases we could implement it so that if SIGMA_MIN is used it will not be triggered.

I have been adding up various small improvements, I could put this fix in as well and do a pull request

**Comment by invemichele** [comment]
I have done both things here https://github.com/invemichele/plumed2/commit/e049b7e45e2dbbeeb3141fd69d0ff50c55b39f13
what do you think @carlocamilloni ?

**Comment by carlocamilloni** [comment]
@invemichele I am wondering if actually sigma_min is enough to fix:           
const double s_rescaling_i=std::max(s_rescaling,sigma_min_[i]/sigma[i]);
if sigma here is 0 you get a segfault irrespectively of sigma_min right? (I mean, at least before your correction)

**Comment by invemichele** [comment]
you are right, it would crash if `sigma[i]=0`, I thought this could never happen...
I changed it so it sets sigma=sigma_min before trying the rescaling. This should make it robust to failure.

While I was looking at it, I realized that I was only adjusting the height when sigma changed due to the shrinking, and not when it was changing because it was adaptive...
Now I rewrote the code so that any change in sigma does affect the height, thus keeping everything properly normalized.
I did some tests, and this does bring some improvements! in particular it makes less severe the cases where the adaptive sigma starts with a quite bad guess, because it is faster to readjust it.

**Pull request closed without merging**
