### PR TITLE
Minor fixes of eABF module

### PR DESCRIPTION
**Pull request by HanatoK**
##### Description

1. Add an option to disable the CZAR estimator.
2. Minor fixes and code cleanups.

##### Target release

I would like my code to appear in release v2.4

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [X] new module contribution or edit of a module authored by you

##### Copyright

- [X] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [X] the module I added or modified contains a `COPYRIGHT` file with the correct license information. I also used the command `cd src && ./headers.sh mymodulename` in order to make sure the headers of the module are correct.

##### Tests

- [X] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by HanatoK** [comment]
I don't know why travis-CI failed, but my own travis-CI test looks right:
https://travis-ci.org/HanatoK/plumed2/builds/294677683

**Comment by GiovanniBussi** [comment]
@HanatoK no problem for the fail, I think it's a problem on travis-ci.

I'll merge this anyway

Giovanni

**Comment by GiovanniBussi** [comment]
@HanatoK by the way, the reason why your travis-ci works is that there are extra tests performed only while testing pull requests, and the failing test is one of those.

**Comment by GiovanniBussi** [comment]
@HanatoK could you also add a line to CHANGES/v2.4.md (after `Fixes after beta release`) specifying what you changed? Thanks!

Giovanni

**Pull request merged**
