### PR TITLE
Work in progress.   Class for calculating geodesic distances

### PR DESCRIPTION
**Pull request by tavanfran**
##### Description

I have implemented a class that computes geodesic distances within the dimred framework of plumed so that you can use ISOMAP with PLUMED.  This is for the attention of @gtribello 

##### Target release

Whenever it is ready

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [x] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct.

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
This pull request **introduces 2 alerts** when merging dbf589589c3f78706b886b41bff7b7002166511c into 1dd6f692462e72a9dfa337aa93983bbc188577a1 - [view on LGTM.com](https://lgtm.com/projects/g/plumed/plumed2/rev/pr-c361cda34afcdad4273f1e9fb323fa9d941f266f)

**new alerts:**

* 2 for Empty branch of conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by gtribello** [comment]
Hello @GiovanniBussi 

This is a student from the extended software development workshop I was at earlier in the week.  I set up the pull request to show him how it is done even though the code was not finished.  Hopefully, he will continue to work on it during the coming weeks and will eventually have something that can be merged at some point in the future.

**Comment by tavanfran** [comment]
Dear @gtribello and @GiovanniBussi ,

I completed the Geodesic_distance module for PLUMED, which contains the Dijkstra's algorithm. This finds the shortest path between configurations.
The module seems to work properly: it compiles into PLUMED and it runs without errors. I tried also with a retest and it runs.
I have a c++ software with the same features of the module that can be used to see the shortest path between points using two different approaches: the nearest neighbors method (where only the first N neighbors are considered for calculation) and the epsilon method (where a cutoff distance is used for the calculation).
Please let me know if you also want the short code in c++ to see the path and if I have to modify something in the Geodesic_distance module.
I will make the pull-request asap.

**Comment by gtribello** [comment]
Hello @tavanfran 

Sorry for the slow reply on this.  Your code is currently failing the continuous integration tests.  It looks to me like it is not managing to compile plumed.  Can you have a look at the error messages to see if you can fix the problems.  We can then talk about how to proceed.  

To see the error message go here:

https://travis-ci.org/github/plumed/plumed2/builds/653419407?utm_medium=notification&utm_source=github_status

If you click on the red crosses you should be able to look at the log.

Good luck and stay well

**Comment by tavanfran** [comment]
Hello @gtribello ,

I am checking the errors and I think I found it, but I am not sure. In my Mac the new module complies, but gives the warning 
warning: variable length arrays are a C99 feature [-Wvla-extension]
Could this error be the problem? If yes, the related line is 
double h[getNumberOfDataPoints()][getNumberOfDataPoints()];
In C++11 this expression is not supported. So, if this is the problem, how can I define a 2D matrix in C++11?
Thanks for your help!!!

**Comment by gtribello** [comment]
Yes that would be the problem.  Replace it with a Matrix like this:

Add this to the header

#include "tools/Matrix.h"

You can then declare a matrix like this:

Matrix<double> h( getNumberOfDataPoints(), getNumberOfDataPoints() );

That should then work because I you can use this form of access:

h[i][j];

Good luck

**Pull request closed without merging**
