### PR TITLE
Tetsuyamorishita patch 1

### PR DESCRIPTION
**Pull request by tetsuyamorishita**
##### Description

We are now contributing a new module for LogMFD/PD and TAMD/d-AFED calculations.

##### Target release

I would like my code to appear in release __v2.5__

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers
- [ ] changes to a module not authored by you
- [X] new module contribution or edit of a module authored by you

##### Copyright

- [ ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [X] the module I added or modified contains a `COPYRIGHT` file with the correct license information. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct.

##### Tests

- [X] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
Thanks a lot for your contribution!

To include it we need you to fix issues on Travis-Ci. In particular, you should solve these warnings:
````
[logmfd/LogMFD.cpp:0] (error) :plmd_astyle: astyle not satisfied
[logmfd/LogMFD.cpp:797] (warning) :invalidPrintfArgType_sint: %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.
[logmfd/LogMFD.cpp:797] (warning) :invalidPrintfArgType_sint: %d in format string (no. 3) requires 'int' but the argument type is 'unsigned int'.
[logmfd/LogMFD.cpp:797] (warning) :invalidPrintfArgType_sint: %d in format string (no. 5) requires 'int' but the argument type is 'unsigned int'.
[logmfd/LogMFD.cpp:814] (warning) :invalidPrintfArgType_sint: %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.
````
and make the test less sensitive to numerical noise (see failure of [this job](https://travis-ci.org/plumed/plumed2/jobs/466963124))

**Comment by GiovanniBussi** [comment]
I also do not see the `COPYRIGHT` file. Make sure that running `cd src && ./header.sh mymodulename` works correctly.

**Comment by tetsuyamorishita** [comment]
Hello @GiovanniBussi 
Thanks for your suggestions. It seems now our contributions have passed the check.
Please let me know if you find any other issues on the contribution.
Tetsuya

**Comment by GiovanniBussi** [comment]
@tetsuyamorishita please notice that I rebased your branch on v2.5 and separated the commits.

Please add the module documentation in the user-doc directory (just fill the `xxxxx` placeholders).

I think in a while the online manual should be updated.

Thanks again for your contribution!

**Comment by tetsuyamorishita** [comment]
Hi Giovanni,

I am now sending herewith the module documentation file, since it seems I cannot do “push access” for uploading to v2.5
(instead, I have uploaded LOGMFDMOD.md to tetsuyamorishita/plumed2/user-doc,
https://github.com/tetsuyamorishita/plumed2/tree/master/user-doc).

Please let me know if you find some mistakes or any.

Cheers,
Tetsuya

**Pull request closed without merging**
