### PR TITLE
Improve coverage secondarystructure/AntibetaRMSD

### PR DESCRIPTION
**Pull request by Mertcan-Puncist**
##### Description

this pull request focuses on enhancing the coverage test result for the secondarystructure/AntibetaRMSD.cpp

### 1- secondarystructure/AntibetaRMSD

i coppyed this original test

* regtest/secondarystructure/rt33

modified and name it          

* secondarystructure/AntibetaRMSD

to cover:

- secondarystructure/AntibetaRMSD.cpp

**covered secondarystructure/AntibetaRMSD.cpp lines|** 

>      119           0 :   } else if( style=="intra") {

### 2- regtest/secondarystructure/rt-coverage-parabetarmsd-parabeta-intra

i coppyed this original test

* regtest/secondarystructure/rt33

modified and name it          

* rt-coverage-parabetarmsd-parabeta-intra

to cover:

- secondarystructure/ParabetaRMSD.cpp

**covered secondarystructure/ParabetaRMSD.cpp lines|** 

     120           0 :   } else if( style=="intra") {
     121             :     intra_chain=true; inter_chain=false;

### 3-  regtest/secondarystructure/rt-coverage-parabetarmsd-parabeta

i coppyed this original test

* regtest/secondarystructure/rt33

modified and name it          

* rt-coverage-parabetarmsd-parabeta

to cover:

- secondarystructure/ParabetaRMSD.cpp

**covered secondarystructure/ParabetaRMSD.cpplines|** 

     118           0 :   } else if( style=="inter") {
     119             :     intra_chain=false; inter_chain=true;

##### Target release

I would like my code to appear in release __v2.9_

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [x] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [x] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by carlocamilloni** [comment]
Is this still in progress @Mertcan-Puncist ?

**Comment by Mertcan-Puncist** [comment]
> Is this still in progress @Mertcan-Puncist i
this one just for the testing the pull request .i have to add comment lines to be clear . thanks for letting me know .

**Comment by Mertcan-Puncist** [comment]
> Is this still in progress @Mertcan-Puncist ?

its ready to go . please take a look at it

**Comment by carlocamilloni** [comment]
@Mertcan-Puncist I see that you are also covering for PARABETA here, is this covering features that are not covered in the other parabeta test? other reasons?

**Comment by Mertcan-Puncist** [comment]
> @Mertcan-Puncist I see that you are also covering for PARABETA here, is this covering features that are not covered in the other parabeta test? other reasons?

i am not covering for PARABETA in this 1 test. this test just copy of original regtest file name regtest/secondarystructure/rt33 . this original test has some lines about PARABETA but i didnt made any changes in that parts .  thats why this is has no business with PARABETA . 

i just modified lines that includes ANTIBETARMSD . so its just covers secondarystructure/AntibetaRMSD.cpp

While you're asking this, I have 2 tests that covers some lines in secondarystructure/ParabetaRMSD, I'll add them in this branch right away

**Comment by Mertcan-Puncist** [comment]
tests and explanations are ready for review

**Pull request merged**
