### PR TITLE
Added patches for NAMD (versions 2.12 and git-latest 2.13b2)

### PR DESCRIPTION
**Pull request by dvdesolve**
Hello! I've created patches for the NAMD 2.12 and latest git version (2.13b2). NAMD compiles with them successfully and we're using it for about a year with no problems.

There is only one point for you to know. With the transition to the charm-6.8.2 in the latest git release of NAMD the shared-linking option during patching not working anymore - seems like new `charmc` have a nasty bug and when you're trying to compile NAMD with shared-linked PLUMED `charmc` can't find necessary Charm++ libs at the last stage of linking `namd2` executable. The only way to use PLUMED with the latest NAMD is to employ static linking.

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
@dvdesolve thanks a lot! I was wondering if patching with `--runtime` works instead. Could you provide some screenshot of the errors you receive when linking with `--shared`?

**Comment by dvdesolve** [comment]
I'm unsure but with `--runtime` I wasn't able to build NAMD too. I only have two log files for the `--shared` build (IIRC it's the default) - with and without PLUMED patch

[with.txt](https://github.com/plumed/plumed2/files/2549590/with.txt)
[without.txt](https://github.com/plumed/plumed2/files/2549591/without.txt)

(Some errors are in Russian but I think there is no problem with them). If I understand it right this error arises when new `charmc` see `libplumed.so` in the command line and generates erroneous command for the linker

**Comment by GiovanniBussi** [comment]
Moved to #405 (rebased)

**Comment by GiovanniBussi** [comment]
@dvdesolve I just opened a new request to rebase yours. Thanks a lot!

Concerning your link error, it looks like there is some other subtle difference between the two configurations. The only change in the linking option produced by the patch should be the addition of `$(PLUMED_LOAD)` to the linked libraries. On the other hand, your log files seem to have more differences. In particular:

"with" links with ` -L/home/viktor/build/pkg/namd/NAMD_2.12_Source/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so`

"without" links with `-L.rootdir/charm-6.8.2/multicore-linux64/bin/../lib`

Can you check if the not-found files (e.g. `liblmoduleGreedyRefineLB.so`) are perhaps in one of the two paths and not in the other?

**Comment by dvdesolve** [comment]
There are listings of these directories contents relative to `multicore-linux64` dir:
```
[viktor@desolve-lab ~/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64]$ ls -lha lib_so/
итого 8,0K
drwxr-xr-x 2 viktor viktor 4,0K ноя  5 21:55 .
drwxr-xr-x 9 viktor viktor 4,0K ноя  5 21:55 ..
-rw-r--r-- 1 viktor viktor    0 ноя  5 21:55 .charmso
[viktor@desolve-lab ~/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64]$ ls -lha bin/../lib
итого 11M
drwxr-xr-x 2 viktor viktor 4,0K ноя  5 21:58 .
drwxr-xr-x 9 viktor viktor 4,0K ноя  5 21:55 ..
-rw-r--r-- 1 viktor viktor  31K ноя  5 21:58 libccs-client.a
-rw-r--r-- 1 viktor viktor 4,6M ноя  5 21:57 libck.a
-rw-r--r-- 1 viktor viktor  13K ноя  5 21:58 libckf.a
-rw-r--r-- 1 viktor viktor 1,8K ноя  5 21:58 libckmain.a
-rw-r--r-- 1 viktor viktor 5,1K ноя  5 21:58 libckqt.a
-rw-r--r-- 1 viktor viktor 547K ноя  5 21:58 libconv-core.a
-rw-r--r-- 1 viktor viktor 102K ноя  5 21:58 libconv-cplus-n.a
-rw-r--r-- 1 viktor viktor 102K ноя  5 21:58 libconv-cplus-y.a
-rw-r--r-- 1 viktor viktor 431K ноя  5 21:58 libconv-ldb.a
-rw-r--r-- 1 viktor viktor 3,2K ноя  5 21:58 libconv-partition.a
-rw-r--r-- 1 viktor viktor 350K ноя  5 21:58 libconv-util.a
-rw-r--r-- 1 viktor viktor 256K ноя  5 21:58 libconv-utilf.a
-rw-r--r-- 1 viktor viktor    0 ноя  5 21:58 libglobal-swap.a
-rw-r--r-- 1 viktor viktor 1,1K ноя  5 21:58 libldb-bluegene.a
-rw-r--r-- 1 viktor viktor  28K ноя  5 21:58 libldb-neighbor.a
-rw-r--r-- 1 viktor viktor 8,1K ноя  5 21:58 libldb-none.a
-rw-r--r-- 1 viktor viktor 9,8K ноя  5 21:58 libldb-rand.a
-rw-r--r-- 1 viktor viktor 9,7K ноя  5 21:58 libldb-spray.a
-rw-r--r-- 1 viktor viktor 9,8K ноя  5 21:58 libldb-test.a
-rw-r--r-- 1 viktor viktor  17K ноя  5 21:58 libldb-workstealing.a
-rw-r--r-- 1 viktor viktor  14K ноя  5 21:58 libmemory-default.a
-rw-r--r-- 1 viktor viktor  51K ноя  5 21:58 libmemory-gnu.a
-rw-r--r-- 1 viktor viktor  54K ноя  5 21:58 libmemory-isomalloc.a
-rw-r--r-- 1 viktor viktor  54K ноя  5 21:58 libmemory-leak.a
-rw-r--r-- 1 viktor viktor  14K ноя  5 21:58 libmemory-os.a
-rw-r--r-- 1 viktor viktor  21K ноя  5 21:58 libmemory-os-isomalloc.a
-rw-r--r-- 1 viktor viktor  21K ноя  5 21:58 libmemory-os-leak.a
-rw-r--r-- 1 viktor viktor  19K ноя  5 21:58 libmemory-os-lock.a
-rw-r--r-- 1 viktor viktor  26K ноя  5 21:58 libmemory-os-paranoid.a
-rw-r--r-- 1 viktor viktor  20K ноя  5 21:58 libmemory-os-verbose.a
-rw-r--r-- 1 viktor viktor 2,9K ноя  5 21:58 libmemory-os-wrapper.a
-rw-r--r-- 1 viktor viktor  60K ноя  5 21:58 libmemory-paranoid.a
-rw-r--r-- 1 viktor viktor  52K ноя  5 21:58 libmemory-verbose.a
-rw-r--r-- 1 viktor viktor  50K ноя  5 21:56 libmoduleBlockLB.a
-rw-r--r-- 1 viktor viktor 401K ноя  5 21:58 libmoduleCkIO.a
-rw-r--r-- 1 viktor viktor 105K ноя  5 21:58 libmoduleCkLoop.a
-rw-r--r-- 1 viktor viktor 1,1K ноя  5 21:58 libmoduleCkMulticast.a
-rw-r--r-- 1 viktor viktor  53K ноя  5 21:56 libmoduleComboCentLB.a
-rw-r--r-- 1 viktor viktor  54K ноя  5 21:56 libmoduleCommLB.a
-rw-r--r-- 1 viktor viktor 1,2M ноя  5 21:56 libmoduleCommonLBs.a
-rw-r--r-- 1 viktor viktor 150K ноя  5 21:56 libmodulecompletion.a
-rw-r--r-- 1 viktor viktor 201K ноя  5 21:56 libmoduleDistributedLB.a
-rw-r--r-- 1 viktor viktor  50K ноя  5 21:56 libmoduleDummyLB.a
-rw-r--r-- 1 viktor viktor  60K ноя  5 21:56 libmoduleGreedyCommLB.a
-rw-r--r-- 1 viktor viktor  83K ноя  5 21:56 libmoduleGreedyLB.a
-rw-r--r-- 1 viktor viktor 115K ноя  5 21:56 libmoduleGreedyRefineLB.a
-rw-r--r-- 1 viktor viktor  45K ноя  5 21:56 libmoduleHybridLB.a
-rw-r--r-- 1 viktor viktor   40 ноя  5 21:56 libmoduleHybridLB.dep
-rw-r--r-- 1 viktor viktor 1,8K ноя  5 21:58 libmoduleNDMeshStreamer.a
-rw-r--r-- 1 viktor viktor   19 ноя  5 21:58 libmoduleNDMeshStreamer.dep
-rw-r--r-- 1 viktor viktor  49K ноя  5 21:56 libmoduleNeighborLB.a
-rw-r--r-- 1 viktor viktor  57K ноя  5 21:56 libmoduleNodeLevelLB.a
-rw-r--r-- 1 viktor viktor  75K ноя  5 21:56 libmoduleOrbLB.a
-rw-r--r-- 1 viktor viktor  51K ноя  5 21:56 libmoduleRandCentLB.a
-rw-r--r-- 1 viktor viktor  53K ноя  5 21:56 libmoduleRefineCommLB.a
-rw-r--r-- 1 viktor viktor   17 ноя  5 21:56 libmoduleRefineCommLB.dep
-rw-r--r-- 1 viktor viktor  51K ноя  5 21:56 libmoduleRefineLB.a
-rw-r--r-- 1 viktor viktor  68K ноя  5 21:56 libmoduleRefineSwapLB.a
-rw-r--r-- 1 viktor viktor  50K ноя  5 21:56 libmoduleRotateLB.a
-rw-r--r-- 1 viktor viktor  27K ноя  5 21:58 libmpi-mainmodule.a
-rw-r--r-- 1 viktor viktor  20K ноя  5 21:58 libthreads-context.a
-rw-r--r-- 1 viktor viktor  22K ноя  5 21:58 libthreads-context-memoryalias.a
-rw-r--r-- 1 viktor viktor  20K ноя  5 21:58 libthreads-context-tls.a
-rw-r--r-- 1 viktor viktor  20K ноя  5 21:58 libthreads-default.a
-rw-r--r-- 1 viktor viktor  20K ноя  5 21:58 libthreads-default-tls.a
-rw-r--r-- 1 viktor viktor  150 ноя  5 21:58 libthreads-fibers.a
-rw-r--r-- 1 viktor viktor  22K ноя  5 21:58 libthreads-memoryalias.a
-rw-r--r-- 1 viktor viktor  20K ноя  5 21:58 libthreads-pthreads.a
-rw-r--r-- 1 viktor viktor  18K ноя  5 21:58 libthreads-qt.a
-rw-r--r-- 1 viktor viktor  20K ноя  5 21:58 libthreads-qt-memoryalias.a
-rw-r--r-- 1 viktor viktor  18K ноя  5 21:58 libthreads-qt-tls.a
-rw-r--r-- 1 viktor viktor  20K ноя  5 21:58 libthreads-stackcopy.a
-rw-r--r-- 1 viktor viktor  21K ноя  5 21:58 libthreads-uJcontext.a
-rw-r--r-- 1 viktor viktor  23K ноя  5 21:58 libthreads-uJcontext-memoryalias.a
-rw-r--r-- 1 viktor viktor  21K ноя  5 21:58 libthreads-uJcontext-tls.a
-rw-r--r-- 1 viktor viktor  28K ноя  5 21:58 libtmgr.a
-rw-r--r-- 1 viktor viktor 6,6K ноя  5 21:58 libtrace-converse.a
-rw-r--r-- 1 viktor viktor 1,1K ноя  5 21:58 libtracef_f.a
```
As you can see there are no .so files, only static libs. And this is only the case when line with $(PLUMED_LOAD) enters the game. Seems like `charmc` doing some work wrong...

PS: According to the NAMD git there are final 2.13 version, so you can rename 2.13b2* files simply to 2.13*

**Comment by GiovanniBussi** [comment]
@dvdesolve static libs instead of dynamic ones I think is not a problem. What surprises me is that that by defining`$(PLUMED_LOAD)` you are automatically changing the path from ...../lib to ...../lib_so. That's really weird.

I will open an issue in case someone else have time to investigate better this. Thanks a lot!

Giovanni

**Comment by jcphill** [comment]
Have you tried not using "--build-shared" but rather "--no-build-shared" when building Charm++?

**Comment by jcphill** [comment]
I think the best workaround would be to use PLUMED_LOAD="-L/path/to/plumed/lib -lplumed -ldl" rather than listing /path/to/plumed/lib/libplumed.so explicitly as a file.

**Pull request closed without merging**
