### PR TITLE
Change to fixzeros.sh script in regtests

### PR DESCRIPTION
**Pull request by valsson**
##### Description

Change to fixzeros.sh script in regtests to make it more general. For example, now values of the form `-0.00` are correctly handled. This change is needed to make the PR #759 pass the CI tests.

This passes all CI tests, see https://github.com/ves-code/plumed2-ves/actions/runs/1482785956 

##### Target release

I would like my code to appear in release v2.8

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
Good point. These are true zeros right? (Any number of zeros followed by a space or new line)

**Comment by valsson** [comment]
Yes, it should capture anything of the form `0.0....0`, there is perhaps some other way to do this

**Comment by valsson** [comment]
For example, 

`echo "-0.0000000 -0.00000  -0.00 -0.0 -0.000000 -0.0000010000" | sed "s/-\(0\.0*0 \)/ \1/g;  s/-\(0\.0*0$\)/ \1/g"`

will generate 

` 0.0000000  0.00000   0.00  0.0  0.000000 -0.0000010000` 
(the white space is not correct due to some formating of the comment, but it is correctly preserved in the terminal)

**Comment by valsson** [comment]
The current script would change something like `-0.00034` to `0.00034`, I recall I had some issues with this in the past but I solved it differently.

**Comment by GiovanniBussi** [comment]
Yes it makes sense thanks for fixing it!

**Pull request merged**
