### PR TITLE
Update VES targets TD_MULTI*

### PR DESCRIPTION
**Pull request by PabloPiaggi**
##### Description

This PR fixes a bug in TD_MULTICANONICAL and TD_MULTITHERMAL_MULTIBARIC, and also introduces some improvements. The bug fix is connected to the calculation of the grid containing the logarithm of the target distribution. The main improvement is the addition of a value EPSILON that prevents the target distribution from becoming 0 and thus yielding an infinite free energy. Some of the issues fixed here were reported by @dkozuch .

##### Target release

I would like my code to appear in any release

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers
- [x] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

##### Tests

- [x] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on Travis-CI.

### CODE REVIEW

**Comment by PabloPiaggi** [comment]
The "MacPorts, Xcode 9.4, all modules" build in Travis CI is failing. I have the impression that it is not connected to the changes in this PR. Should I do something? Thank you.

**Comment by GiovanniBussi** [comment]
You are right it's unrelated (`Error: Portfile is from the future - check date and time of your system`, unfortunately happens from time to time).

**Comment by GiovanniBussi** [comment]
I think @valsson should approve this.

**Comment by valsson** [comment]
Hello, 

There are only changes to files that @PabloPiaggi previously contributed, so far as I am concerned, it can be merged. 

Omar

**Comment by GiovanniBussi** [comment]
@PabloPiaggi I am planning to merge this in master (to be v2.7). Could you please add a short notice in [this file](https://github.com/plumed/plumed2/blob/master/CHANGES/v2.7.md) explaining what's new? Thanks

**Comment by PabloPiaggi** [comment]
> @PabloPiaggi I am planning to merge this in master (to be v2.7). Could you please add a short notice in [this file](https://github.com/plumed/plumed2/blob/master/CHANGES/v2.7.md) explaining what's new? Thanks

Yes, I will write one or two sentences now

**Comment by PabloPiaggi** [comment]
> @PabloPiaggi I am planning to merge this in master (to be v2.7). Could you please add a short notice in [this file](https://github.com/plumed/plumed2/blob/master/CHANGES/v2.7.md) explaining what's new? Thanks

Done

**Comment by GiovanniBussi** [comment]
Thanks a lot @PabloPiaggi for your contribution!

**Pull request merged**
