### PR TITLE
Masterclass 22.3

### PR DESCRIPTION
**Pull request by invemichele**
##### Description
Here is my masterclass for tomorrow.

I also unified the numbering of previous 2022 masterclasses, so that they will appear in the proper order both on the website and in the source:
- 22-0x -> name of the file and web page
- 22.x   -> name in the index and title of the page

##### Target release

I would like my code to appear in release __master__

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [x] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
Thanks @invemichele !! Good that you fixed the file names. I think we have to fix the links in the plumed.org/masterclass as well

**Comment by invemichele** [comment]
Actually, now that I check, in the end I only changed the file name, and not the web page name. So the links are safe.

If we want to have more consistency in the web pages naming, the one of funnel metadynamics should be changed from `masterclass-22-1.html` to `masterclass-22-01.html`
Note that this is different from the masterclass of 2021, but those were less than 10...

**Comment by spiwokv** [comment]
Sorry, it was my mistake to introduce "0" to the file name and to chapter IDs. I will unify everything with the first masterclass of 2022.

**Comment by GiovanniBussi** [comment]
Hi! I think the 0 is fine and will be needed to have the correct order in the end

**Pull request merged**
