### PR TITLE
Do not hold Python's GIL when running commands

### LINKED ISSUE #1128: Consider releasing the GIL in the Python interface
The current Python interface to PLUMED uses cython to call the C++ code, and by default cython takes and hold the Global Interpreter Lock (GIL).

Unfortunately, this conflicts with the `metatensor` (and likely `pytorch`) modules, because PyTorch checks that the GIL is not held when running `backward()` (i.e. computing gradients): 

https://github.com/pytorch/pytorch/blob/f69bf005f7b3be70b9a38ba663e6bc825dfe7ffd/torch/csrc/autograd/python_engine.cpp#L130-L135

This means that trying to use PLUMED with a `METATENSOR` action from Python will always fail with the above error.

Would it be possible to annotate the functions in `python/cplumed.pxd` with `@cython.nogil`? (cf https://cython.readthedocs.io/en/latest/src/userguide/nogil.html)

This would fix the above problem, and should be fine to do as long a there is no function call from PLUMED back to the Python interpreter. I'm not sure if the latter is the case or not though (i.e. can someone define custom CV as pure Python scripts?)

### PR DESCRIPTION
**Pull request by Luthaf**
##### Description

Fixes #1128. I can confirm this fixes the issue for `metatensor` actions.

However, I'm not sure how to test that `pycv` still works fine, is it included in the CI test suite?

##### Type of contribution

- [x] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [ ] new module contribution or edit of a module authored by you

##### Copyright

- [x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [ ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by Iximiel** [comment]
> However, I'm not sure how to test that `pycv` still works fine, is it included in the CI test suite?

pycv has its workflow run in `linux(-pycv-mpi-)`, which runs its regtests in its plugin subdirectory.

But we do not have a "run pycv from plumed in python" test that runs on the CI

**Comment by GiovanniBussi** [comment]
> > However, I'm not sure how to test that `pycv` still works fine, is it included in the CI test suite?
> 
> pycv has its workflow run in `linux(-pycv-mpi-)`, which runs its regtests in its plugin subdirectory.
> 
> But we do not have a "run pycv from plumed in python" test that runs on the CI

This possibly means that, due to these GIL issues, also "run pycv from plumed in python" is not working? I though @Iximiel was testing this at least locally, is this correct? Otherwise I think we need a test

**Comment by Iximiel** [comment]
> 
> This possibly means that, due to these GIL issues, also "run pycv from plumed in python" is not working? I though @Iximiel was testing this at least locally, is this correct? Otherwise I think we need a test

I tried, and I think I need to find a solution to this:

```
what():  Can't add new modules after the interpreter has been initialized
```

**Comment by Luthaf** [comment]
Is this an error on the current master or with these changes?

**Comment by Iximiel** [comment]
> Is this an error on the current master or with these changes?

The error is in master, don't worry.

I opened a separate issue about it

**Comment by Luthaf** [comment]
@Iximiel and @GiovanniBussi, could one of you do a review of this? Thanks!

**Comment by GiovanniBussi** [comment]
I think it's fine, I can merge it. For the records, @Luthaf could you reply to these questions? I would then add some documentation in the pyx file after merging to keep track:
- Why both the `nogil` attribute in the `pxd` file and the `with nogil():` in the `pyx` file?
- Other calls to C functions in the `pyx` file are not protected (e.g. `cplumed.plumed_error_init()`). I guess we cannot have a single `with nogil():` at the beginning of a block where we use python. However, would it be recommended to have a block around every call to a `cplumed.*` function? Which are pros and cons?
- Beside affecting the correctness in metatensor, is this change expected to affect performance in a positive or negative way?

Thanks!

**Comment by Luthaf** [comment]
> Why both the nogil attribute in the pxd file and the with nogil(): in the pyx file?

The one we really want is the `with.nogil` in pyx, asking cython to release the GIL when running this function. The `nogil` in pxd are declarative, telling cython that these are pure C functions that don't require the GIL. They are required because otherwise cython refuses to run the `with.nogil` block.

> Other calls to C functions in the pyx file are not protected (e.g. cplumed.plumed_error_init()). I guess we cannot have a single with nogil(): at the beginning of a block where we use python. However, would it be recommended to have a block around every call to a cplumed.* function? Which are pros and cons?

So anytime the code is constructing Python objects, you can not have `nogil` around it, meaning you can not have a global `with nogil` around the whole thing. 

It could make sense to put a `with nogil` block around all calls to `cplumed` functions, this would allow for more complex calculations to happen in the other functions. It might also help for pycv (and in general any time a function call ends up back inside a Python interpreter) by preventing a deadlock where both py-plumed and the interpreter trying to get the same lock.

I only wrapped `cmd` since that's seems like the only function that would be likely to end back inside a Python interpreter as far as I understand the API.

> Beside affecting the correctness in metatensor, is this change expected to affect performance in a positive or negative way?

No,  I don't think so. This would potentially allow to have multiple Python threads call into plumed concurrently, but I don't even know if that's a supported use case anyway, and doing actual multi threading in Python is very painful.

**Pull request merged**
