### PR TITLE
Fix for S2CM manual generation

### PR DESCRIPTION
**Pull request by valsson**
##### Description

Fixes some issues with incorrect manual generation for the S2CM module. 

##### Target release

I would like my code to appear in release v2.8

##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [x] new module contribution or edit of a module authored by you

##### Copyright

- [ ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [x] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [ ] I added a new regtest or modified an existing regtest to validate my changes.
- [ ] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by valsson** [comment]
However, this only partially fixes the issue, it does not fully work correctly. 
It seems that because there is a numerical character in `S2CMMOD_COLVAR`, the script to replace `@S2CMMOD_COLVAR@` when going from `S2CMMOD.md` to `S2CMMODPP.md` does not work correctly. If I change `S2CMMOD` to `SSCMMOD` everywhere in the module documentation it works fine. 

So using a numerical character in the name of the module documentation (i.e., in X1XX_COLVAR`), breaks the script to do the replacement in the `PP.md` files. 

I could fix this by renaming the module documation. But maybe it would be better to solve this in the manual generation script.

**Comment by GiovanniBussi** [comment]
@valsson is it due to these two lines perhaps:
```
user-doc/extract:keywords=`grep "@[A-Z_]*@" *.md | awk -F"@" '{print $2}' | sort | uniq`
user-doc/extract:grep -Ev '^ *@[A-Z:_]*@ *$' ${file}PP.$extension > tmp;
```

Maybe the search should be replaced with something like `@[A-Z_][A-Z0-9_]*@`. Can you check if this solves the problem?

**Comment by GiovanniBussi** [comment]
@valsson after 4478523 will be pushed to https://www.plumed.org/doc-v2.8/user-doc/html/index.html we will see if it works on Github Actions. Then let me know if I should merge this anyway. Thanks!

**Comment by valsson** [comment]
Thanks @GiovanniBussi! 

This PR should be merged regardless as it fixes wrong names used in `PLUMEDOC S2CMMOD_COLVAR S2CM` that is independent of the issue with numerical character in the module names.

**Pull request merged**
