### PR TITLE
Two new CVs for the membrane fusion process.

### PR DESCRIPTION
**Pull request by lautarodibartolo**
##### Type of contribution

- [ ] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ ] changes to a module not authored by you
- [X] new module contribution or edit of a module authored by you

##### Copyright

- [ ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.

- [X] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 

##### Tests

- [X] I added a new regtest or modified an existing regtest to validate my changes.
- [X] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
If you plan to maintain the code I would suggest:
- Adding a `COPYRIGHT` file with your name.
- Add the documentation so that this appears as a contributed module (see one of the other contributed modules for examples

I also think you forgot to add the `src/membranefusion/Makefile` file, so I guess this will not work on GH Actions

**Comment by lautarodibartolo** [comment]
Hello Giovanni, thanks for your comments:
- COPYRIGHT added.
- The `src/membranefusion/Makefile` was added before (#804).

What do you mean for documentation? I wrote the documentation of each CV .cpp file.

Thanks!

**Comment by lautarodibartolo** [comment]
@GiovanniBussi no problem! Starting now.

**Comment by lautarodibartolo** [comment]
@GiovanniBussi,

I've been writing the documentation for the additional module, but I can't get it to appear in the list of additional modules or the collective variables to stop appearing in the general section of CVs.

Here I can notice that my module is not in the list:
AdditionalModules

At the bottom the FUSIONPORENUCLEATIONP and FUSIONPOREEXPANSIONP:
COLVARS

My additional module documentation:
MembraneFusion

I will push those files but I feel that something is wrong. Sorry in advance.

Regards,

**Comment by valsson** [comment]
Hello, 

1) 
In the CV cpp files, try changing 

`//+PLUMEDOC COLVAR FUSIONPOREEXPANSIONP`

to

`//+PLUMEDOC MEMBRANEFUSIONMOD_COLVAR FUSIONPOREEXPANSIONP`


Then in the `user-doc/MEMBRANEFUSIONMOD.md file` 

2)
Use 
`@MEMBRANEFUSIONMOD_COLVAR@` 
to allow the doc parser to automatically to insert the CVs instead of listing them yourself. 

Similar to what I did here: https://raw.githubusercontent.com/plumed/plumed2/master/user-doc/S2CMMOD.md 

The last time I did this, I had similar issues and making sure step 1) is done correctly helped and doc parser decteded the module correctly. Thus, step 1) is critical, while I think that step 2) is optional. 

Regards,
Omar

**Comment by lautarodibartolo** [comment]
@valsson thanks!!

Now this is working as it should 👍  I followed both steps.

Greetings,

**Comment by GiovanniBussi** [comment]
Merging now. Thanks for your contribution!!!!

**Pull request merged**
